### PR TITLE
Update the upstream version of finufft

### PR DESCRIPTION
**Pull request by dfm**

### CODE REVIEW

**Comment by lgarrison** [comment]
I think we *probably* want to compile the static library with `-fPIC`? I.e. `target_compile_options(-fPIC PRIVATE finufft)` in our CMake. Maybe using a finufft shared library instead would be better for codes that use both finufft and jax-finufft, but that's probably a corner case and requires care with rpath and auditwheel.

**Comment by lgarrison** [comment]
It looks like we need to set the `POSITION_INDEPENDENT_CODE` CMake property on (1) the finufft libs and (2) their dependencies. I don't know of an elegant way to set this on (2), so for now I'm just doing it explicitly. This probably means we should ask the finufft folks to add a `FINUFFT_POSITION_INDEPENDENT_CODE` flag.

In any case, this seems to have pushed the MacOS error to a missing FFTW dep. Maybe we need an explicit FFTW dependency in our CMake? Not sure why Ubuntu would work in that case, maybe because it's installing the headers in system paths?

**Review by lgarrison — APPROVED** [review]
LGTM! Although we might want to wait until finufft 2.3 lands, which should be in the next week.

**Comment by lgarrison** [comment]
finufft 2.3 is out! I updated the vendored dependency here, and things look good. Ready to merge?

**Comment by dfm** [comment]
Thanks!!

**Pull request merged**
